---
title: "Resources for R training for Faculty of Arts"
author: "David Osborne"
date: now
date-modified: last-modified
date-format: iso
format:
  html: default
  pdf: default
---

# Books (free online)

-   James Long & Paul Teetor (2019) *R Cookbook.* <https://rc2e.com/>
-   Winston Chang (2018) *R Graphics Cookbook.* <https://r-graphics.org/>
-   Garrett Grolemund & Hadley Wickham (2016) *R for Data Science.* <https://r4ds.had.co.nz/>
    -   uses Tidyverse
-   Julia Silge & David Robinson (2017) *Text Mining With R.* <https://www.tidytextmining.com/>
-   Robin Lovelace *et al.* (2019) *Geocomputation with R.* <https://r.geocompx.org/>
-   Yihui Xie (2022) *RMarkdown: the Definitive Guide.* <https://bookdown.org/yihui/rmarkdown/>

# Books (in print)

-   Brunsdon & Comber (2014) *An Introduction to R for Spatial Analysis & Mapping*. London: SAGE Publications.
-   Carlson (2017) *Quantitative Methods in Archaeology Using R*. Cambridge: Cambridge University Press.

# Guides

-   R Studio: <https://docs.posit.co/ide/user/>
-   R Studio cheatsheets: <https://www.rstudio.com/resources/cheatsheets/>
-   *Finding your way to R*: <https://education.rstudio.com/learn/>
-   Bookdown: <https://bookdown.org/>
-   Winston Chang: *Cookbook for R.* <http://www.cookbook-r.com>
-   Quarto: <https://quarto.org/>

# Subject-related guides

## General

-   CRAN Task Views: <https://www.stats.bris.ac.uk/R/> then click on Task Views

## Statistics

-   Ismay and Kim (2018) *A modern dive into data with R: An introduction to statistical and data sciences via R*. <https://moderndive.com/index.html>
-   Chester Ismay (2018) *Statistical inference: a Tidy approach*. <https://ismayc.github.io/talks/ness-infer/slide_deck.html#1>

## Archaeology

-   Mike Baxter (2015) *Notes on Quantitative Archaeology and R.* <https://www.academia.edu/12545743/Notes_on_Quantitative_Archaeology_and_R>
-   Ben Marwick (2018) *Using R and Related Tools for Reproducible Research in Archaeology.* <http://www.practicereproducibleresearch.org/case-studies/benmarwick.html>
    -   in Kitzes *et al.* (eds.) (2018) *The Practice of Reproducible Research: Case Studies and Lessons from the Data-Intensive Sciences.* <http://www.practicereproducibleresearch.org/>
-   Rchaeology Community resources list: <https://rchaeology.github.io/resources/archaeology/>
    -   Mastodon: @Rchaeology\@archaeo.social

# Examples

-   R graph gallery:  <https://www.r-graph-gallery.com>
-   Ben Marwick's list of archaeology publications with R code
    -   <https://github.com/benmarwick/ctv-archaeology#publications-that-include-r-code>
    -   also `@archpaperscode` Twitter bot: <https://twitter.com/archpaperscode>
-   Tidy Tuesday 2022 examples gallery: <https://github.com/deepdk/TidyTuesday-2022>
    -   Tom Mock explains the Tidy Tuesday project at <https://www.youtube.com/watch?v=H8rhQOj7vDY>

# Video

-   Simon Jackson's *Wrangling Data in the Tidyverse* (useR! 2018 workshops & tutorials)
    -   Part 1 (1:16:10): {{< video https://www.youtube.com/embed/E-Vvg8uzcVM >}}
    -   Part 2 (1:11:43): {{< video https://www.youtube.com/embed/DwWH1mTerOc >}}

# Packages

-   Tidyverse <https://www.tidyverse.org/> 
    -   Paper: Wickham *et al.* (2019)  <https://doi.org/10.21105/joss.01686> 

# Reusable code, open science, reproducibility

-   Code quality: [Trisovic, A. *et al.* (2022) A large-scale study on research code quality and execution. *Scientific Data* 9, 60](https://www.nature.com/articles/s41597-022-01143-6)
    -   see *Best practices and recommendations* section

# Tools

-   [Rstudio](https://posit.co/products/open-source/rstudio/) --- widely-used Integrated Development Environment (IDE) for R
-   [Tabula](https://tabula.technology/) --- extracting CSVs from PDFs
-   Git --- for version control
    -   [GitHub](https://github.com/about) --- sharing code

    -   [Github Pages](https://pages.github.com/) --- for websites

    -   [Using Git with R](https://happygitwithr.com/)

# Teaching materials (for the tutors)

-   RStudio Education: <https://education.rstudio.com/teach/>
